title: Indraja Punna
logo: /assets/img/logo.png
description: My journey from a Python Django web application developer/Engineering director to AI & ML
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
