title: <p align="center"> Indraja Punna </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/indraja-punna-76853834/">LinkedIn</a> |
  <a href="https://github.com/IndrajaPunna">GitHub</a>
  
  <br>   
  My journey from a Python Django web application developer/Engineering director to AI & ML
  <br>
  </p>



theme: jekyll-theme-minimal